# Generated by Django 4.2.9 on 2026-03-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FIRReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fir_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fir_reports",
                        to="emergency.emergencycase",
                    ),
                ),
            ],
            options={
                "db_table": "fir_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
