"""
FIR app models – stores AI-generated First Information Reports.
"""
from django.db import models
from apps.emergency.models import EmergencyCase


class FIRReport(models.Model):
    """
    A First Information Report (FIR) draft generated by Gemini AI,
    linked to an emergency case.
    """
    case = models.ForeignKey(
        EmergencyCase,
        on_delete=models.CASCADE,
        related_name="fir_reports"
    )
    fir_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "fir_reports"
        ordering = ["-created_at"]

    def __str__(self):
        return f"FIR for Case {self.case.case_id}"
